// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBkIJKcL-RMq9eebDrPU-NayPxpzISUY',
    appId: '1:1027032251330:web:efd7cd2bea9395cfaff45b',
    messagingSenderId: '1027032251330',
    projectId: 'akbarimandiwholesale',
    authDomain: 'akbarimandiwholesale.firebaseapp.com',
    storageBucket: 'akbarimandiwholesale.appspot.com',
    measurementId: 'G-9GPTSCKPEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYagct14deM1dmoyC-YVq5zjYpJI0RQtk',
    appId: '1:1027032251330:android:0768a0e210c9e099aff45b',
    messagingSenderId: '1027032251330',
    projectId: 'akbarimandiwholesale',
    storageBucket: 'akbarimandiwholesale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfh4Euy4SXAmHLghbGJTSNLo6CwfyO150',
    appId: '1:1027032251330:ios:3524bea4bad4ce89aff45b',
    messagingSenderId: '1027032251330',
    projectId: 'akbarimandiwholesale',
    storageBucket: 'akbarimandiwholesale.appspot.com',
    iosClientId: '1027032251330-u37lkhqcosida6rdo8j5frecj2s9f9oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.akbarimandiwholesale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfh4Euy4SXAmHLghbGJTSNLo6CwfyO150',
    appId: '1:1027032251330:ios:3524bea4bad4ce89aff45b',
    messagingSenderId: '1027032251330',
    projectId: 'akbarimandiwholesale',
    storageBucket: 'akbarimandiwholesale.appspot.com',
    iosClientId: '1027032251330-u37lkhqcosida6rdo8j5frecj2s9f9oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.akbarimandiwholesale',
  );
}
